version: "3.9"
services:
  peerbanhelper:
    image: @IMAGE@
    restart: unless-stopped
    container_name: "peerbanhelper"
    volumes:
      - ./:/app/data
    network_mode: host
    stop_grace_period: 30s